In [2]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data
np.random.seed(0)


In [4]:
print(np.random.randn(2,4))

[[ 0.69377315 -0.15957344 -0.13370156  1.07774381]
 [-1.12682581 -0.73067775 -0.38487981  0.09435159]]


In [7]:
print(np.zeros((1 , 4)))

[[0. 0. 0. 0.]]


In [17]:
x = np.array(['a', 'b', 'c'], dtype=object)
print(np.outer(x, 4))

[['aaaa']
 ['bbbb']
 ['cccc']]


In [2]:
def relu(x):
    return np.maximum(0 ,x)


def relu_derivative(x):
    return np.where(x > 0, 1, 0)

In [6]:
import numpy as np

np.random.seed(0)



learning_rate = 0.001

inputs = np.array([[1, 2, 3, 4]])  # Reshaped to (1, 4)

neurons = 4

weights = np.random.randn(4, neurons)  # Shape (4,4)
biases = np.zeros((1, neurons))  # Shape (1, 4)

for i in range(100):
    # Forward Pass
    z = np.dot(inputs, weights) + biases  # Shape (1, 4)
    a = relu(z)

    # Backward Pass
    drelu = relu_derivative(z)
    
    dz = a * drelu  # Element-wise multiplication (Hadamard product)
    dweights = np.dot(inputs.T, dz)  # Shape (4,4)
    dbiases = np.sum(dz, axis=0, keepdims=True)  # Shape (1,4)
    
    dinputs = np.dot(dz, weights.T)  # Shape (1,4)

    # Gradient Descent Update
    weights -= learning_rate * dweights
    biases -= learning_rate * dbiases

    print(f"Iteration {i+1}: Weights:\n{weights}\nBiases:\n{biases}")

    y = np.sum(a)

    # Calculate loss
    loss = y ** 2

    print(loss)







Iteration 1: Weights:
[[ 1.75581868  0.39999311  0.97365149  2.2332575 ]
 [ 1.85109066 -0.97760607  0.93991542 -0.1666286 ]
 [-0.12791984  0.41010621  0.12878408  1.43136642]
 [ 0.72810307  0.12101863  0.42351724  0.30313154]]
Biases:
[[-0.00823366 -0.0001641  -0.0050865  -0.0076357 ]]
446.05248942302285
Iteration 2: Weights:
[[ 1.74784026  0.3998341   0.96872267  2.22585851]
 [ 1.83513383 -0.97792409  0.93005779 -0.18142658]
 [-0.1518551   0.40962918  0.11399762  1.40916945]
 [ 0.6961894   0.12038259  0.40380197  0.27353558]]
Biases:
[[-0.01621208 -0.00032311 -0.01001532 -0.01503469]]
418.82589152113115
Iteration 3: Weights:
[[ 1.74010918  0.39968002  0.96394664  2.21868889]
 [ 1.81967165 -0.97823226  0.92050574 -0.19576582]
 [-0.17504836  0.40916694  0.09966955  1.38766058]
 [ 0.66526505  0.11976627  0.38469788  0.2448571 ]]
Biases:
[[-0.02394317 -0.00047719 -0.01479134 -0.02220431]]
393.2611779285728
Iteration 4: Weights:
[[ 1.73261775  0.39953072  0.95931868  2.21174153]
 [ 1.80468

In [11]:

np.random.seed(0)



learning_rate = 0.001

inputs = np.array([[1, 2, 3, 4]])  # Reshaped to (1, 4)

neurons = 4

weights = np.random.randn(4, neurons)  # Shape (4,4)
biases = np.zeros((1, neurons))  # Shape (1, 4)

z = np.dot( inputs , weights) + biases

print(z)
a = relu(z)
dz = relu_derivative(z)
print(a)

print(inputs.T)

dweights = np.dot(inputs.T, dz)
dbiases = np.sum(a, axis=0, keepdims=True)

dinputs = np.dot(a, weights.T)

print(dinputs)

[[8.23366267 0.16409702 5.08649846 7.63569661]]
[[8.23366267 0.16409702 5.08649846 7.63569661]]
[[1]
 [2]
 [3]
 [4]]
[[36.67940642 18.89337968 11.05457748 11.09164   ]]


In [ ]:
X , y = spiral_data(100 , 3)

class layer_dense:
    def __init__(self , inputs , neurons):
        self.weights = np.random.randn(inputs , neurons)
        self.baises = np.zeros((1, neurons))

    def forward(self , x_inputs):
        self.output = np.dot( x_inputs , self.weights) + self.baises

    def backword(self , x_inputs):
        z = self.weights*x_inputs + self.baises
        a = relu(z)
        y = np.sum(a)

        loss = y**2



    # Backward pass
    def backward(self, dvalues):
        # Gradients on parameters
        self.dweights = np.dot(self.inputs.T, dvalues)
        self.dbiases = np.sum(dvalues, axis=0, keepdims=True)
        # Gradient on values
        self.dinputs = np.dot(dvalues, self.weights.T)

    
    

# dw = np.random.randn(4 , 1)
# db = np.random.randn(4 ,1)
# X

array([[ 0.00000000e+00,  0.00000000e+00],
       [ 2.99555668e-03,  9.64660797e-03],
       [ 1.28809693e-02,  1.55628484e-02],
       [ 2.99747911e-02,  4.44809463e-03],
       [ 3.93124610e-02,  9.32828459e-03],
       [ 8.28829718e-04,  5.04982492e-02],
       [ 5.34835151e-02,  2.85062834e-02],
       [ 4.17361950e-02,  5.70752124e-02],
       [ 5.54633933e-02,  5.87686815e-02],
       [ 8.16038348e-02,  4.00659076e-02],
       [ 8.91875104e-02,  4.74197058e-02],
       [ 1.07160836e-01, -2.93638266e-02],
       [ 1.21183204e-01, -2.64751646e-03],
       [ 1.28777727e-01,  2.56794752e-02],
       [ 1.41112962e-01, -9.22449475e-03],
       [ 1.50579469e-01, -1.68126315e-02],
       [ 1.13476365e-01, -1.15077793e-01],
       [ 1.71552512e-01, -7.51816565e-03],
       [ 1.67186847e-01, -7.14591446e-02],
       [ 1.91325874e-01,  1.50793230e-02],
       [ 1.36771890e-01,  1.48679561e-01],
       [ 1.35606422e-01, -1.63114398e-01],
       [ 1.04024754e-01, -1.96370992e-01],
       [ 2.